server:
  port: 8080

spring:
  application:
    name: cell-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://account-service:8081
          predicates:
            - Path=/api/v1/accounts/**
        - id: auth-service
          uri: http://auth-service:8082
          predicates:
            - Path=/api/v1/auth/**
        - id: authz-service
          uri: http://authz-service:8083
          predicates:
            - Path=/api/v1/authz/**

management: # Configuracion del Actuator
  endpoints:
    web:
      exposure:
        include: gateway
